### ISSUE TITLE
Remove "v" prefix from package version

### ISSUE THREAD

**Issue by theboolean** [ripaclub/zf2-mailman#22]
Removing the "v" prefix will allow composer to use operands in the package versions, such as "~" or ">="

**Comment by leogr** [comment]
It should work anyway, prefixes are ignored by composer.
In your composer.json you have to use the version x.y.z (without "v", ignoring prefixes) and can use operands, like the following examples:
```
"ripaclub/zf2-mailman": "0.2.0"

"ripaclub/zf2-mailman": "~0.2"

"ripaclub/zf2-mailman": ">=0.2.0"
```

What kind of issue are you  encounter?

PS: I've noticed a typo in the README `"ripaclub/zf2-mailman": "v0.2.0"` must be `"ripaclub/zf2-mailman": "0.2.0"`

**Comment by theboolean** [comment]
Yes, sorry, my bad: I was using the "v" prefix like stated in the README. However, in the PR that I've made, I also fixed that typo.
