### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by jeanbelhache** [ripaclub/zf2-mailman#25]
Hi,

The package can't be imported.
The requested package ripaclub/zf2-mailman could not be found in any version, there may be a typo in the package name.

**Comment by visa4** [comment]
Hi,

package is on [packagist](https://packagist.org/packages/ripaclub/zf2-mailman).

Try `composer require ripaclub/zf2-mailman`.

**Comment by jeanbelhache** [comment]
Okay, so it generate a new line with 0.3.0 version (not 0.3.1).
But next i got an error :
 Problem 1
    - Installation request for ripaclub/zf2-mailman ^0.3.0 -> satisfiable by ripaclub/zf2-mailman[v0.3.0].
    - Conclusion: remove zendframework/zendframework 2.2.10
    - Conclusion: don't install zendframework/zendframework 2.2.10
    - ripaclub/zf2-mailman v0.3.0 requires zendframework/zend-mime ~2.4 -> satisfiable by zendframework/zend-mime[2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.5.1].
    - don't install zendframework/zend-mime 2.4.0|don't install zendframework/zendframework 2.2.10
    - don't install zendframework/zend-mime 2.4.1|don't install zendframework/zendframework 2.2.10
    - don't install zendframework/zend-mime 2.4.2|don't install zendframework/zendframework 2.2.10
    - don't install zendframework/zend-mime 2.4.3|don't install zendframework/zendframework 2.2.10
    - don't install zendframework/zend-mime 2.5.0|don't install zendframework/zendframework 2.2.10
    - don't install zendframework/zend-mime 2.5.1|don't install zendframework/zendframework 2.2.10
    - Installation request for zendframework/zendframework == 2.2.10.0 -> satisfiable by zendframework/zendframework[2.2.10].


Installation failed, reverting ./composer.json to its original content.

**Comment by visa4** [comment]
ripaclub/zf2-mailman ^0.3.0 requires zendframework >= 2.4.
 
If you want to use it you have to switch to zendframework >= 2.4.

**Comment by jeanbelhache** [comment]
it works.
Thank you
